name: dwdcmd
author: dwd_madmac
version: 1.0
main: net.downwithdestruction.dwdcmd.DwDCmd
description: Core Commands for DwD Gaming.
depend: [ProtocolLib]

commands:
    fly:
        usage: /<command> [player]
        description: Toggles creative flymode for yourself or a player.
    flyspeed:
        usage: /<command>  [speed] (player)
        description: Changes a players flyspeed.
    helmet:
        usage: /<command> [player]
        description: Set a custom helmet that is in your hand.

permissions:
    dwdcmd.command.fly:
        description: Allows you to toggle creative flymode.
        default: op
    dwdcmd.command.fly.others:
        description: Allows you to toggle creative flymode for another player.
        default: op
    dwdcmd.command.fly.exempt:
        description: Stop other players from toggling your flymode.
        default: op
##########################################################################################
    dwdcmd.command.flyspeed:
        description: Allows you to change your flyspeed.
        default: op
    dwdcmd.command.flyspeed.others:
        description: Allows you to change flyspeed for another player.
        default: op
    dwdcmd.command.flyspeed.exempt:
        description: Stop other players from changing your flyspeed.
        default: op
##########################################################################################
    dwdcmd.command.helmet:
        description: Allows you to change your custom helmet.
        default: op
    dwdcmd.command.helmet.others:
        description: Allows you to change another players custom helmet.
        default: op
    dwdcmd.command.helmet.exempt:
        description: stop other players from changing your custom helmet.
        default: op